name: PhotoAtom Full Infrastructure Deployment

on:
  workflow_dispatch:

jobs:
  bootstrap_cluster:
    name: PhotoAtom Cluster Setup Deployment
    uses: PhotoAtom/automations/.github/workflows/run-workflow.yml@main
    with:
      REPOSITORY_DEFINITION: PhotoAtom/bootstrap-cluster
      WORKFLOW_DEFINITION: cluster-base.yml
    secrets: inherit

  minio:
    name: PhotoAtom MinIO Deployment
    needs: [bootstrap_cluster]
    uses: PhotoAtom/automations/.github/workflows/run-workflow.yml@main
    with:
      REPOSITORY_DEFINITION: PhotoAtom/minio
      WORKFLOW_DEFINITION: tofu-deploy.yml
    secrets: inherit

  postgres:
    name: PhotoAtom CloudNative PG Deployment
    needs: [minio]
    uses: PhotoAtom/automations/.github/workflows/run-workflow.yml@main
    with:
      REPOSITORY_DEFINITION: PhotoAtom/postgres
      WORKFLOW_DEFINITION: tofu-deploy.yml
    secrets: inherit

  valkey:
    name: PhotoAtom Valkey Deployment
    needs: [minio]
    uses: PhotoAtom/automations/.github/workflows/run-workflow.yml@main
    with:
      REPOSITORY_DEFINITION: PhotoAtom/valkey
      WORKFLOW_DEFINITION: tofu-deploy.yml
    secrets: inherit

  keycloak:
    name: PhotoAtom Keycloak Deployment
    needs: [postgres]
    uses: PhotoAtom/automations/.github/workflows/run-workflow.yml@main
    with:
      REPOSITORY_DEFINITION: PhotoAtom/keycloak
      WORKFLOW_DEFINITION: tofu-deploy.yml
    secrets: inherit

  backend:
    name: PhotoAtom Backend Deployment
    needs: [keycloak, valkey]
    uses: PhotoAtom/automations/.github/workflows/run-workflow.yml@main
    with:
      REPOSITORY_DEFINITION: PhotoAtom/backend
      WORKFLOW_DEFINITION: tofu-deploy.yml
    secrets: inherit

  frontend:
    name: PhotoAtom Frontend Deployment
    needs: [backend]
    uses: PhotoAtom/automations/.github/workflows/run-workflow.yml@main
    with:
      REPOSITORY_DEFINITION: PhotoAtom/frontend
      WORKFLOW_DEFINITION: tofu-deploy.yml
    secrets: inherit
